spring:
  application:
    name: chessriend

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/chessriend
    username: chessriend
    password: chessriend

  flyway:
    url: jdbc:postgresql://localhost:5432/chessriend
    user: chessriend
    password: chessriend
    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
